/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Query:{
		hello:{
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		getMenuTree:{
			id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			visible:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			from:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			to:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		getMenuList:{
			id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			visible:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			from:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			to:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			pageNo:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			},
			pageSize:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		getRoleList:{
			id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			isDefault:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			from:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			to:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			includeMenu:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			pageNo:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			},
			pageSize:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		getUserList:{
			id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			phone:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			email:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			from:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			to:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			includeRole:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			pageNo:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			},
			pageSize:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	DateTime: "String",
	UserGenderEnum: "enum",
	JSONObject: "String",
	Mutation:{
		login:{
			password:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createMenu:{
			input:{
				type:"CreateMenuInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		editMenu:{
			input:{
				type:"EditMenuInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		removeMenus:{
			menuIds:{
				type:"String",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createRole:{
			input:{
				type:"CreateRoleInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		editRole:{
			input:{
				type:"EditRoleInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		removeRoles:{
			roleIds:{
				type:"String",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createUser:{
			input:{
				type:"CreateUserInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		editUser:{
			input:{
				type:"EditUserInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		removeUsers:{
			userIds:{
				type:"String",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		resetUserPassword:{
			userId:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	CreateMenuInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		icon:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		pId:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		orderBy:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		path:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		component:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		visible:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		permission:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	EditMenuInput:{
		id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		icon:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		pId:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		orderBy:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		path:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		component:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		visible:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		permission:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CreateRoleInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		key:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		level:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:true
		},
		menuIds:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	EditRoleInput:{
		id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		key:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		level:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		menuIds:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CreateUserInput:{
		username:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		avatar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		gender:{
			type:"UserGenderEnum",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		nickname:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		phone:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		note:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		roleIds:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	EditUserInput:{
		id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		avatar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gender:{
			type:"UserGenderEnum",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		nickname:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		phone:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		note:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		roleIds:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	Query:{
		hello:"String",
		me:"LoginUser",
		getMenuTree:"JSONObject",
		getMenuList:"MenuPageResult",
		getRoleList:"RolePageResult",
		getUserList:"UserPageResult"
	},
	LoginUser:{
		id:"ID",
		createdAt:"DateTime",
		updatedAt:"DateTime",
		username:"String",
		avatar:"String",
		gender:"UserGenderEnum",
		email:"String",
		nickname:"String",
		phone:"String",
		note:"String",
		roles:"Role",
		loginTime:"DateTime",
		menus:"Menu",
		permissions:"String",
		isSuperAdmin:"Boolean"
	},
	Role:{
		id:"ID",
		createdAt:"DateTime",
		updatedAt:"DateTime",
		name:"String",
		level:"Float",
		key:"String",
		isDefault:"Boolean",
		menus:"Menu"
	},
	Menu:{
		id:"ID",
		createdAt:"DateTime",
		updatedAt:"DateTime",
		name:"String",
		icon:"String",
		pId:"String",
		orderBy:"Float",
		path:"String",
		component:"String",
		visible:"Boolean",
		permission:"String",
		type:"String",
		children:"Menu"
	},
	MenuPageResult:{
		data:"Menu",
		totalCount:"Float",
		hasNextPage:"Boolean"
	},
	RolePageResult:{
		data:"Role",
		totalCount:"Float",
		hasNextPage:"Boolean"
	},
	UserPageResult:{
		data:"User",
		totalCount:"Float",
		hasNextPage:"Boolean"
	},
	User:{
		id:"ID",
		createdAt:"DateTime",
		updatedAt:"DateTime",
		username:"String",
		avatar:"String",
		gender:"UserGenderEnum",
		email:"String",
		nickname:"String",
		phone:"String",
		note:"String",
		roles:"Role"
	},
	Mutation:{
		login:"LoginResult",
		logout:"BaseResponse",
		createMenu:"BaseResponse",
		editMenu:"BaseResponse",
		removeMenus:"BaseResponse",
		createRole:"BaseResponse",
		editRole:"BaseResponse",
		removeRoles:"BaseResponse",
		createUser:"BaseResponse",
		editUser:"BaseResponse",
		removeUsers:"BaseResponse",
		resetUserPassword:"BaseResponse"
	},
	LoginResult:{
		code:"Float",
		msg:"String",
		data:"LoginType"
	},
	LoginType:{
		accessToken:"String"
	},
	BaseResponse:{
		code:"Float",
		msg:"String"
	},
	BaseResult:{
		"...on BaseResponse": "BaseResponse",
		code:"Float",
		msg:"String"
	}
}