/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	ArticleStatusEnum: "enum" as const,
	CreateArticleCategoryInputInput:{

	},
	CreateArticleInputInput:{

	},
	CreateCommentInputInput:{

	},
	CreateDoctorScheduleInputInput:{
		date:"LocalDate"
	},
	CreateMenuInputInput:{
		type:"MenuTypeEnum"
	},
	CreateOrgInputInput:{
		orgType:"OrgTypeEnum"
	},
	CreatePhysicalExamInputInput:{
		date:"Date"
	},
	CreateRoleInputInput:{

	},
	CreateUserInputInput:{
		gender:"GenderEnum"
	},
	Date: `scalar.Date` as const,
	DefaultRoleEnum: "enum" as const,
	Direction: "enum" as const,
	FileProviderEnum: "enum" as const,
	FileQueryPageParamInput:{
		provider:"FileProviderEnum"
	},
	GenderEnum: "enum" as const,
	LocalDate: `scalar.LocalDate` as const,
	LocalDateTime: `scalar.LocalDateTime` as const,
	Long: `scalar.Long` as const,
	MenuQueryPageParamInput:{

	},
	MenuQueryParamInput:{
		type:"MenuTypeEnum"
	},
	MenuTypeEnum: "enum" as const,
	MessageTypeEnum: "enum" as const,
	Mutation:{
		deleteMenu:{

		},
		unpublishArticle:{

		},
		updateArticle:{
			input:"UpdateArticleInputInput"
		},
		updateArticleCategory:{
			input:"UpdateArticleCategoryInputInput"
		},
		createArticleCategory:{
			input:"CreateArticleCategoryInputInput"
		},
		updateRole:{
			input:"UpdateRoleInputInput"
		},
		deleteComment:{

		},
		revoke:{

		},
		createRole:{
			input:"CreateRoleInputInput"
		},
		updateOrg:{
			input:"UpdateOrgInputInput"
		},
		deletePhysicalExam:{

		},
		createComment:{
			input:"CreateCommentInputInput"
		},
		updateMenu:{
			input:"UpdateMenuInputInput"
		},
		updateDoctorSchedule:{
			input:"updateDoctorScheduleInputInput"
		},
		createDoctorSchedule:{
			input:"CreateDoctorScheduleInputInput"
		},
		createMenu:{
			input:"CreateMenuInputInput"
		},
		createOrg:{
			input:"CreateOrgInputInput"
		},
		deleteArticleCategory:{

		},
		createArticle:{
			input:"CreateArticleInputInput"
		},
		deleteOrg:{

		},
		deleteDoctorSchedule:{

		},
		publishArticle:{

		},
		updateRoleMenu:{
			input:"UpdateRoleMenuInputInput"
		},
		updateUser:{
			input:"UpdateUserInputInput"
		},
		sendMessage:{
			input:"SendMessageInputInput"
		},
		updateComment:{
			input:"UpdateCommentInputInput"
		},
		deleteRole:{

		},
		deleteArticle:{

		},
		updateUserProfile:{
			input:"UpdateUserProfileInputInput"
		},
		registerUser:{
			input:"UserRegisterInputInput"
		},
		loginByAccount:{
			input:"UserLoginInputInput"
		},
		deleteUser:{

		},
		createUser:{
			input:"CreateUserInputInput"
		},
		deleteFileById:{

		},
		createPhysicalExam:{
			input:"CreatePhysicalExamInputInput"
		}
	},
	NullHandling: "enum" as const,
	OrgTypeEnum: "enum" as const,
	Query:{
		queryMenuList:{
			param:"MenuQueryParamInput"
		},
		queryCommentPage:{
			specification:"QueryCommentPageSpecificationInput"
		},
		queryUserPage:{
			specification:"QueryUserPageSpecificationInput"
		},
		messageSession:{

		},
		queryPhysicalExamPage:{
			specification:"QueryPhysicalExamPageSpecificationInput"
		},
		queryArticle:{

		},
		queryDoctorSchedulePage:{
			specification:"QueryDoctorSchedulePageSpecificationInput"
		},
		queryMenuTree:{
			param:"MenuQueryPageParamInput"
		},
		queryRolePage:{
			param:"RoleQueryParamInput"
		},
		queryRole:{

		},
		queryUserList:{
			specification:"QueryUserSpecificationInput"
		},
		queryMessagePage:{
			specification:"QueryMessagePageSpecificationInput"
		},
		queryArticlePage:{
			specification:"QueryArticlePageSpecificationInput"
		},
		queryOrgPage:{
			specification:"QueryOrgPageSpecificationInput"
		},
		queryMessageSessionPage:{
			specification:"QueryMessageSessionPageSpecificationInput"
		},
		queryFilePage:{
			param:"FileQueryPageParamInput"
		},
		queryArticleCategory:{
			specification:"QueryArticleCategorySpecificationInput"
		},
		queryUser:{

		}
	},
	QueryArticleCategorySpecificationInput:{

	},
	QueryArticlePageSpecificationInput:{

	},
	QueryCommentPageSpecificationInput:{

	},
	QueryDoctorSchedulePageSpecificationInput:{
		date:"LocalDate"
	},
	QueryMessagePageSpecificationInput:{

	},
	QueryMessageSessionPageSpecificationInput:{

	},
	QueryOrgPageSpecificationInput:{
		orgType:"OrgTypeEnum"
	},
	QueryPhysicalExamPageSpecificationInput:{
		date:"Date"
	},
	QueryUserPageSpecificationInput:{

	},
	QueryUserSpecificationInput:{

	},
	RoleQueryParamInput:{

	},
	SendMessageInputInput:{
		type:"MessageTypeEnum"
	},
	UpdateArticleCategoryInputInput:{

	},
	UpdateArticleInputInput:{

	},
	UpdateCommentInputInput:{

	},
	UpdateMenuInputInput:{
		type:"MenuTypeEnum"
	},
	UpdateOrgInputInput:{
		orgType:"OrgTypeEnum"
	},
	UpdateRoleInputInput:{

	},
	UpdateRoleMenuInputInput:{

	},
	UpdateUserInputInput:{
		gender:"GenderEnum"
	},
	UpdateUserProfileInputInput:{

	},
	UserLoginInputInput:{

	},
	UserRegisterInputInput:{

	},
	updateDoctorScheduleInputInput:{
		date:"LocalDate"
	}
}

export const ReturnTypes: Record<string,any> = {
	Article:{
		author:"User",
		authorId:"String",
		category:"ArticleCategory",
		categoryId:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		html:"String",
		id:"String",
		image:"String",
		markdown:"String",
		metaDescription:"String",
		metaTitle:"String",
		publishedAt:"LocalDateTime",
		publishedBy:"String",
		status:"ArticleStatusEnum",
		title:"String",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	ArticleCategory:{
		articles:"Article",
		children:"ArticleCategory",
		createdAt:"LocalDateTime",
		createdBy:"String",
		icon:"String",
		id:"String",
		name:"String",
		parent:"ArticleCategory",
		parentId:"String",
		sort:"Int",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	BaseEntity:{
		"...on Article": "Article",
		"...on ArticleCategory": "ArticleCategory",
		"...on Comment": "Comment",
		"...on DoctorSchedule": "DoctorSchedule",
		"...on File": "File",
		"...on Menu": "Menu",
		"...on Message": "Message",
		"...on MessageSession": "MessageSession",
		"...on Org": "Org",
		"...on PhysicalExam": "PhysicalExam",
		"...on Role": "Role",
		"...on User": "User",
		createdAt:"LocalDateTime",
		createdBy:"String",
		id:"String",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	Comment:{
		content:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		id:"String",
		ip:"String",
		location:"String",
		org:"Org",
		orgId:"String",
		updatedAt:"LocalDateTime",
		updatedBy:"String",
		user:"User",
		userId:"String"
	},
	Date: `scalar.Date` as const,
	DoctorSchedule:{
		createdAt:"LocalDateTime",
		createdBy:"String",
		date:"LocalDate",
		doctor:"User",
		doctorId:"String",
		id:"String",
		org:"Org",
		orgId:"String",
		shift:"String",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	File:{
		bucket:"String",
		category:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		fileHash:"String",
		fileName:"String",
		fileSize:"Int",
		id:"String",
		mimeType:"String",
		originName:"String",
		provider:"FileProviderEnum",
		updatedAt:"LocalDateTime",
		updatedBy:"String",
		url:"String"
	},
	LocalDate: `scalar.LocalDate` as const,
	LocalDateTime: `scalar.LocalDateTime` as const,
	LoginSessionResult:{
		createdAt:"LocalDateTime",
		current:"Boolean",
		expired:"Boolean",
		id:"String",
		ip:"String"
	},
	Long: `scalar.Long` as const,
	Menu:{
		children:"Menu",
		component:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		frame:"Boolean",
		icon:"String",
		id:"String",
		name:"String",
		parent:"Menu",
		parentId:"String",
		path:"String",
		permission:"String",
		roles:"Role",
		sort:"Int",
		title:"String",
		type:"MenuTypeEnum",
		updatedAt:"LocalDateTime",
		updatedBy:"String",
		visible:"Boolean"
	},
	Message:{
		content:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		fromUser:"User",
		fromUserId:"String",
		id:"String",
		session:"MessageSession",
		sessionId:"String",
		toUser:"User",
		toUserId:"String",
		type:"MessageTypeEnum",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	MessageSession:{
		createdAt:"LocalDateTime",
		createdBy:"String",
		fromUser:"User",
		fromUserId:"String",
		id:"String",
		toUser:"User",
		toUserId:"String",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	Mutation:{
		deleteMenu:"Boolean",
		unpublishArticle:"Boolean",
		updateArticle:"Article",
		updateArticleCategory:"ArticleCategory",
		createArticleCategory:"ArticleCategory",
		updateRole:"Role",
		deleteComment:"Boolean",
		revoke:"Boolean",
		createRole:"Role",
		updateOrg:"Org",
		deletePhysicalExam:"Boolean",
		createComment:"Comment",
		updateMenu:"Menu",
		logout:"Boolean",
		updateDoctorSchedule:"DoctorSchedule",
		createDoctorSchedule:"DoctorSchedule",
		createMenu:"Menu",
		createOrg:"Org",
		deleteArticleCategory:"Boolean",
		createArticle:"Article",
		deleteOrg:"Boolean",
		deleteDoctorSchedule:"Boolean",
		publishArticle:"Boolean",
		updateRoleMenu:"Boolean",
		updateUser:"User",
		sendMessage:"Message",
		updateComment:"Comment",
		deleteRole:"Boolean",
		deleteArticle:"Boolean",
		updateUserProfile:"Boolean",
		registerUser:"Boolean",
		loginByAccount:"String",
		deleteUser:"Boolean",
		createUser:"User",
		deleteFileById:"Boolean",
		createPhysicalExam:"PhysicalExam"
	},
	Order:{
		direction:"Direction",
		ignoreCase:"Boolean",
		nullHandlingHint:"NullHandling",
		property:"String"
	},
	Org:{
		address:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		id:"String",
		latitude:"Float",
		lead:"User",
		leadId:"String",
		longitude:"Float",
		name:"String",
		openTime:"String",
		orgType:"OrgTypeEnum",
		updatedAt:"LocalDateTime",
		updatedBy:"String"
	},
	Page_Article:{
		content:"Article",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_Comment:{
		content:"Comment",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_DoctorSchedule:{
		content:"DoctorSchedule",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_File:{
		content:"File",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_Message:{
		content:"Message",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_MessageSession:{
		content:"MessageSession",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_Org:{
		content:"Org",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_PhysicalExam:{
		content:"PhysicalExam",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_Role:{
		content:"Role",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Page_User:{
		content:"User",
		first:"Boolean",
		hasContent:"Boolean",
		hasNext:"Boolean",
		hasPrevious:"Boolean",
		last:"Boolean",
		nextOrLastPageable:"Pagination",
		nextPageable:"Pagination",
		number:"Int",
		numberOfElements:"Int",
		pageable:"Pagination",
		previousOrFirstPageable:"Pagination",
		previousPageable:"Pagination",
		size:"Int",
		sort:"Sorting",
		totalElements:"Long",
		totalPages:"Int"
	},
	Pagination:{
		pageNumber:"Int",
		pageSize:"Int",
		sort:"Sort"
	},
	PhysicalExam:{
		bloodPressure:"String",
		cholesterolLevel:"Float",
		createdAt:"LocalDateTime",
		createdBy:"String",
		date:"Date",
		doctorNotes:"String",
		heartRate:"Int",
		height:"Float",
		id:"String",
		org:"Org",
		orgId:"String",
		result:"String",
		sugarLevel:"Float",
		updatedAt:"LocalDateTime",
		updatedBy:"String",
		user:"User",
		userId:"String",
		weight:"Float"
	},
	Query:{
		app:"String",
		userInfo:"UserInfoResult",
		queryMenuList:"Menu",
		queryCommentPage:"Page_Comment",
		queryArticleCategoryTree:"ArticleCategory",
		queryUserPage:"Page_User",
		messageSession:"MessageSession",
		queryPhysicalExamPage:"Page_PhysicalExam",
		queryArticle:"Article",
		queryDoctorSchedulePage:"Page_DoctorSchedule",
		queryMenuTree:"Menu",
		queryRolePage:"Page_Role",
		queryLoginSessionList:"LoginSessionResult",
		queryRole:"Role",
		queryUserList:"User",
		queryAllRoleList:"Role",
		queryMessagePage:"Page_Message",
		queryDefaultRole:"DefaultRoleEnum",
		queryArticlePage:"Page_Article",
		queryOrgPage:"Page_Org",
		queryMessageSessionPage:"Page_MessageSession",
		queryFilePage:"Page_File",
		queryArticleCategory:"ArticleCategory",
		queryUser:"User"
	},
	Role:{
		createdAt:"LocalDateTime",
		createdBy:"String",
		default:"Int",
		id:"String",
		key:"String",
		level:"Int",
		menuIds:"String",
		menus:"Menu",
		name:"String",
		updatedAt:"LocalDateTime",
		updatedBy:"String",
		users:"User"
	},
	Sort:{
		orders:"Order"
	},
	Sorting:{
		orders:"Order"
	},
	User:{
		avatar:"String",
		createdAt:"LocalDateTime",
		createdBy:"String",
		email:"String",
		gender:"GenderEnum",
		id:"String",
		job:"String",
		nickName:"String",
		note:"String",
		org:"Org",
		orgId:"String",
		phone:"String",
		roles:"Role",
		updatedAt:"LocalDateTime",
		updatedBy:"String",
		userName:"String"
	},
	UserInfoResult:{
		avatar:"String",
		email:"String",
		gender:"GenderEnum",
		id:"String",
		menus:"Menu",
		nickName:"String",
		passwordEnable:"Boolean",
		permissions:"String",
		phone:"String",
		roles:"Role",
		superAdmin:"Boolean",
		userName:"String"
	}
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}