/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    Content: typeof import('./components/layout/Content.vue')['default']
    EmojiPicker: typeof import('./components/EmojiPicker/index.vue')['default']
    FilePond: typeof import('./components/FilePond/index.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./components/layout/Logo.vue')['default']
    MenuIcon: typeof import('./components/MenuIcon/index.vue')['default']
    MenuItem: typeof import('./components/layout/MenuItem.vue')['default']
    PostEditor: typeof import('./components/post/PostEditor/index.vue')['default']
    PostEditorHeader: typeof import('./components/post/PostEditorHeader.vue')['default']
    PostFooter: typeof import('./components/post/PostFooter.vue')['default']
    PostHeader: typeof import('./components/post/PostHeader.vue')['default']
    PostImage: typeof import('./components/post/PostImage.vue')['default']
    PostItem: typeof import('./components/post/PostItem.vue')['default']
    PostSider: typeof import('./components/post/PostSider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/layout/SideMenu.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
  }
}
