/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/layout/dashboard/Breadcrumb.vue')['default']
    Content: typeof import('./components/layout/dashboard/Content.vue')['default']
    FilePone: typeof import('./components/file-pone/index.vue')['default']
    Header: typeof import('./components/layout/dashboard/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./components/layout/dashboard/Logo.vue')['default']
    MdEditor: typeof import('./components/md-editor/index.vue')['default']
    MDViewer: typeof import('./components/md-editor/MDViewer.vue')['default']
    MenuIcon: typeof import('./components/menu-icon/index.vue')['default']
    MenuItem: typeof import('./components/layout/dashboard/MenuItem.vue')['default']
    PostEditor: typeof import('./components/post/post-editor/index.vue')['default']
    PostEditorHeader: typeof import('./components/post/PostEditorHeader.vue')['default']
    PostFooter: typeof import('./components/layout/post/PostFooter.vue')['default']
    PostHeader: typeof import('./components/layout/post/PostHeader.vue')['default']
    PostImage: typeof import('./components/post/PostImage.vue')['default']
    PostItem: typeof import('./components/post/PostItem.vue')['default']
    PostSelectTag: typeof import('./components/post/PostSelectTag.vue')['default']
    PostSider: typeof import('./components/post/PostSider.vue')['default']
    PostStar: typeof import('./components/post/PostStar.vue')['default']
    PublishDrawer: typeof import('./components/post/PublishDrawer.vue')['default']
    PublishModal: typeof import('./components/post/PublishDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/layout/dashboard/SideMenu.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    TinymceEditor: typeof import('./components/tinymce-editor/index.vue')['default']
    Viewer: typeof import('./components/md-editor/MDViewer.vue')['default']
  }
}
